packages:
    - 'packages/*'
    - 'apps/*'

catalog:
    '@primeuix/styled': ^0.7.0
    '@primeuix/utils': ^0.6.0
    '@primeuix/forms': ^0.1.0
    '@primeuix/styles': ^1.2.1
    '@primeuix/themes': ^1.2.1
    'tailwindcss-primeui': ^0.6.1
    'primeicons': ^7.0.0

catalogs:
    app:
        'nuxt': 3.15.4
        'vite': 6.0.11
        'sass': 1.45.0
        'sass-loader': 8.0.2
        '@docsearch/js': ^3
        'chart.js': 3.3.2
        'quill': 2.0.0
